version: '2'

services:
    minio:
        image: nginx:alpine
        volumes:
            - ./minio-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.minio.rule=Host(`minio.docker.localhost`)"
            - "traefik.http.routers.minio.tls.domains[0].main=docker.localhost"
            - "traefik.http.routers.minio.tls.domains[0].sans[0]=*.docker.localhost"
            - "traefik.http.services.minio.loadbalancer.server.port=9000"
            - "traefik.http.routers.minio.entryPoints=https"
            - "traefik.docker.network=selion"
        networks:
            - selion
            - default
    minioui:
        image: nginx:alpine
        volumes:
            - ./ui-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.minioui.rule=Host(`minioui.docker.localhost`)"
            - "traefik.http.routers.minioui.tls.domains[0].main=docker.localhost"
            - "traefik.http.routers.minioui.tls.domains[0].sans[0]=*.docker.localhost"
            - "traefik.http.services.minioui.loadbalancer.server.port=9090"
            - "traefik.http.routers.minioui.entryPoints=https"
            - "traefik.docker.network=selion"
        networks:
            - selion
            - default
    minioapi:
        image: quay.io/minio/minio:latest
        restart: always
        command:
            - server
            - /data
            - --console-address
            - ':9090'
        volumes:
            -   minio:/data
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: password
        networks:
            - selion
            - default
volumes:
  minio:


networks:
    selion:
        external: true
